// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXKWM8Qj-CHC5dV9CymfcJ72W8MpoQoE',
    appId: '1:1778221929:web:43af3c7d507f1f2655b3f8',
    messagingSenderId: '1778221929',
    projectId: 'bill-app-44182',
    authDomain: 'bill-app-44182.firebaseapp.com',
    storageBucket: 'bill-app-44182.appspot.com',
    measurementId: 'G-SPNZMXHF95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxUOjwR1dcHABU-sCU06zih-oNGH-39w',
    appId: '1:1778221929:android:301e03e8fb64bcf955b3f8',
    messagingSenderId: '1778221929',
    projectId: 'bill-app-44182',
    storageBucket: 'bill-app-44182.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADd2oyn1X_zt3uXJGi8Am8z9VsIue9LM',
    appId: '1:1778221929:ios:685230064869167d55b3f8',
    messagingSenderId: '1778221929',
    projectId: 'bill-app-44182',
    storageBucket: 'bill-app-44182.appspot.com',
    iosClientId: '1778221929-punih31h5jhb3bsh9egesg3r272cfv7d.apps.googleusercontent.com',
    iosBundleId: 'com.baptiste.bill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADd2oyn1X_zt3uXJGi8Am8z9VsIue9LM',
    appId: '1:1778221929:ios:d5486417a965ec6a55b3f8',
    messagingSenderId: '1778221929',
    projectId: 'bill-app-44182',
    storageBucket: 'bill-app-44182.appspot.com',
    iosClientId: '1778221929-re0d5fc871sv81b2oh0a8lqujelnl3r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bill',
  );
}
